"""
Generate .github/memory-bank/indices/codemap.md

Scans backend/app (Python) and frontend/src (TypeScript/TSX) and emits
a structured symbol index: path → exported classes/functions/types/constants.

Usage:
    python scripts/gen_codemap.py
    python scripts/gen_codemap.py --out docs/codemap.md
"""
from __future__ import annotations

import ast
import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
BACKEND_ROOT = REPO_ROOT / "backend" / "app"
FRONTEND_ROOT = REPO_ROOT / "frontend" / "src"
DEFAULT_OUT = REPO_ROOT / ".github" / "memory-bank" / "indices" / "codemap.md"

# ──────────────────────────────────────────────────────────── Python ──

def _py_first_docstring(node: ast.AST) -> str:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Module)):
        body = node.body  # type: ignore[attr-defined]
        if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant):
            raw = str(body[0].value.value).strip().splitlines()[0][:80]
            return f"  # {raw}"
    return ""

def scan_python_file(path: Path) -> list[str]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return []

    symbols: list[str] = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            doc = _py_first_docstring(node)
            symbols.append(f"  class {node.name}{doc}")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                doc = _py_first_docstring(node)
                prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
                symbols.append(f"  {prefix} {node.name}(){doc}")
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id.isupper():
                    symbols.append(f"  {t.id}  # const")
    return symbols


def scan_backend() -> list[tuple[str, list[str]]]:
    results: list[tuple[str, list[str]]] = []
    for py in sorted(BACKEND_ROOT.rglob("*.py")):
        if "__pycache__" in py.parts or py.name == "__init__.py":
            continue
        rel = py.relative_to(REPO_ROOT).as_posix()
        symbols = scan_python_file(py)
        if symbols:
            results.append((rel, symbols))
    return results


# ──────────────────────────────────────────────────────── TypeScript ──

_TS_EXPORT = re.compile(
    r"^export\s+"
    r"(?:(?:default|abstract|declare)\s+)*"
    r"(?:"
    r"(const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)|"  # const/let/var NAME
    r"(function\*?)\s+([A-Za-z_$][A-Za-z0-9_$]*)|"   # function NAME
    r"(async\s+function\*?)\s+([A-Za-z_$][A-Za-z0-9_$]*)|"  # async function NAME
    r"(class)\s+([A-Za-z_$][A-Za-z0-9_$]*)|"         # class NAME
    r"(type|interface|enum)\s+([A-Za-z_$][A-Za-z0-9_$]*)"  # type/interface/enum NAME
    r")",
    re.MULTILINE,
)

def scan_ts_file(path: Path) -> list[str]:
    try:
        src = path.read_text(encoding="utf-8")
    except Exception:
        return []

    symbols: list[str] = []
    for m in _TS_EXPORT.finditer(src):
        # figure out which group matched
        if m.group(1):   # const/let/var
            symbols.append(f"  {m.group(1)} {m.group(2)}")
        elif m.group(3): # function
            symbols.append(f"  {m.group(3)} {m.group(4)}()")
        elif m.group(5): # async function
            symbols.append(f"  {m.group(5)} {m.group(6)}()")
        elif m.group(7): # class
            symbols.append(f"  class {m.group(8)}")
        elif m.group(9): # type/interface/enum
            symbols.append(f"  {m.group(9)} {m.group(10)}")
    return symbols


def scan_frontend() -> list[tuple[str, list[str]]]:
    results: list[tuple[str, list[str]]] = []
    for ts in sorted(FRONTEND_ROOT.rglob("*")):
        if ts.suffix not in (".ts", ".tsx"):
            continue
        if any(p in ts.parts for p in ("node_modules", "dist", "coverage", "__snapshots__")):
            continue
        if ts.stem.endswith(".test") or ts.stem.endswith(".spec"):
            continue
        rel = ts.relative_to(REPO_ROOT).as_posix()
        symbols = scan_ts_file(ts)
        if symbols:
            results.append((rel, symbols))
    return results


# ──────────────────────────────────────────────────────────── Output ──

def build_markdown(backend: list[tuple[str, list[str]]], frontend: list[tuple[str, list[str]]]) -> str:
    lines: list[str] = []

    lines.append("# Codemap")
    lines.append("")
    lines.append("> Auto-generated by `scripts/gen_codemap.py`. Do NOT edit manually.")
    lines.append("> Regenerate after significant refactors: `python scripts/gen_codemap.py`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Backend ──
    lines.append("## Backend (`backend/app/`)")
    lines.append("")

    # group by top-level module
    groups: dict[str, list[tuple[str, list[str]]]] = {}
    for rel, syms in backend:
        top = rel.split("/")[2] if rel.count("/") >= 2 else "root"
        groups.setdefault(top, []).append((rel, syms))

    for mod in sorted(groups):
        lines.append(f"### `{mod}/`")
        lines.append("")
        for rel, syms in groups[mod]:
            lines.append(f"**`{rel}`**")
            lines.extend(syms)
            lines.append("")

    lines.append("---")
    lines.append("")

    # ── Frontend ──
    lines.append("## Frontend (`frontend/src/`)")
    lines.append("")

    fe_groups: dict[str, list[tuple[str, list[str]]]] = {}
    for rel, syms in frontend:
        parts = rel.split("/")
        top = parts[2] if len(parts) >= 3 else "root"
        fe_groups.setdefault(top, []).append((rel, syms))

    for mod in sorted(fe_groups):
        lines.append(f"### `{mod}/`")
        lines.append("")
        for rel, syms in fe_groups[mod]:
            lines.append(f"**`{rel}`**")
            lines.extend(syms)
            lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate codemap.md")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    print("Scanning backend/app…")
    backend = scan_backend()
    print(f"  {len(backend)} files with exported symbols")

    print("Scanning frontend/src…")
    frontend = scan_frontend()
    print(f"  {len(frontend)} files with exported symbols")

    md = build_markdown(backend, frontend)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"\nWrote {args.out.relative_to(REPO_ROOT)}")
    print(f"  {md.count(chr(10))+1} lines")


if __name__ == "__main__":
    main()
