"""Curated per-domain whitelists for Tavily ``include_domains`` routing.

Maps each :class:`QuestionDomain` to a wide list of authoritative and
collaborative knowledge sources. Used by
:func:`app.agent.source_hints.build_source_hints` to derive the
``include_domains`` hint forwarded to the Tavily plugin.

Tavily applies ``include_domains`` as a **strict filter** (not a soft
boost), so :func:`app.agent.tasks.search._search_one_claim` performs a
retry without the whitelist when the first call returns empty results.
The combination gives an effective "soft" allowlist behaviour.

``QuestionDomain.OTHER`` is intentionally absent: the planner falls back
to :mod:`app.agent.dynamic_allowlist` (one LLM classifier call per run,
cached on ``RunState.dynamic_allowlist``).
"""

from __future__ import annotations

from app.domain.enums import QuestionDomain

WHITELIST: dict[QuestionDomain, tuple[str, ...]] = {
    QuestionDomain.MEDICAL: (
        "pubmed.ncbi.nlm.nih.gov",
        "nih.gov",
        "who.int",
        "cdc.gov",
        "fda.gov",
        "ema.europa.eu",
        "ecdc.europa.eu",
        "nice.org.uk",
        "mayoclinic.org",
        "hopkinsmedicine.org",
        "clevelandclinic.org",
        "nejm.org",
        "thelancet.com",
        "bmj.com",
        "jamanetwork.com",
        "cochrane.org",
        "uptodate.com",
        "medlineplus.gov",
        "cancer.gov",
        "heart.org",
        "diabetes.org",
        "healthline.com",
        "webmd.com",
        "medscape.com",
    ),
    QuestionDomain.LEGAL: (
        "law.cornell.edu",
        "justia.com",
        "courtlistener.com",
        "supremecourt.gov",
        "uscourts.gov",
        "loc.gov",
        "eur-lex.europa.eu",
        "europa.eu",
        "echr.coe.int",
        "oas.org",
        "un.org",
        "icj-cij.org",
        "icc-cpi.int",
        "hrw.org",
        "amnesty.org",
        "americanbar.org",
        "lawsociety.org.uk",
        "scholar.google.com",
        "ssrn.com",
        "jurist.org",
        "lawfare.media",
    ),
    QuestionDomain.FINANCIAL: (
        "sec.gov",
        "ecb.europa.eu",
        "federalreserve.gov",
        "bankofengland.co.uk",
        "imf.org",
        "worldbank.org",
        "bis.org",
        "oecd.org",
        "ft.com",
        "wsj.com",
        "bloomberg.com",
        "reuters.com",
        "economist.com",
        "hbr.org",
        "barrons.com",
        "morningstar.com",
        "investopedia.com",
        "seekingalpha.com",
    ),
    QuestionDomain.TECHNOLOGY: (
        # Standards bodies & primary tech authorities
        "ieee.org",
        "spectrum.ieee.org",
        "acm.org",
        "w3.org",
        "ietf.org",
        "iso.org",
        "nist.gov",
        "developer.mozilla.org",
        "web.dev",
        # Vendor official docs
        "docs.aws.amazon.com",
        "cloud.google.com",
        "learn.microsoft.com",
        # Academic / industry analysis
        "arxiv.org",
        "semanticscholar.org",
        "oreilly.com",
        "thoughtworks.com",
        "martinfowler.com",
        "infoq.com",
        "thenewstack.io",
        "lwn.net",
        # Reputable tech press
        "arstechnica.com",
        "theverge.com",
        "wired.com",
        "spectrum.ieee.org",
        "techcrunch.com",
        "zdnet.com",
        "computerworld.com",
        # Code & projects (kept; useful for verifying live behaviour)
        "github.com",
    ),
    QuestionDomain.SCIENCE: (
        "arxiv.org",
        "biorxiv.org",
        "medrxiv.org",
        "nature.com",
        "science.org",
        "pnas.org",
        "cell.com",
        "plos.org",
        "sciencedirect.com",
        "springer.com",
        "wiley.com",
        "nasa.gov",
        "esa.int",
        "cern.ch",
        "nist.gov",
        "noaa.gov",
        "usgs.gov",
        "doe.gov",
        "nih.gov",
        "scientificamerican.com",
        "newscientist.com",
        "quantamagazine.org",
        "nationalgeographic.com",
        "smithsonianmag.com",
        "semanticscholar.org",
        "researchgate.net",
        "scholar.google.com",
        "zenodo.org",
        "figshare.com",
        "physicsforums.com",
        "mathoverflow.net",
        "math.stackexchange.com",
        "stats.stackexchange.com",
    ),
    QuestionDomain.GEOPOLITICS: (
        "foreignaffairs.com",
        "foreignpolicy.com",
        "cfr.org",
        "brookings.edu",
        "rand.org",
        "csis.org",
        "atlanticcouncil.org",
        "chathamhouse.org",
        "carnegieendowment.org",
        "wilsoncenter.org",
        "iiss.org",
        "ft.com",
        "economist.com",
        "reuters.com",
        "bbc.com",
        "aljazeera.com",
        "nytimes.com",
        "washingtonpost.com",
        "un.org",
        "nato.int",
        "europa.eu",
        "worldpoliticsreview.com",
    ),
    QuestionDomain.BUSINESS: (
        "hbr.org",
        "mckinsey.com",
        "bcg.com",
        "bain.com",
        "deloitte.com",
        "pwc.com",
        "kpmg.com",
        "ey.com",
        "ft.com",
        "bloomberg.com",
        "economist.com",
        "wsj.com",
        "businessinsider.com",
        "fortune.com",
        "fastcompany.com",
        "inc.com",
        "entrepreneur.com",
        "sloanreview.mit.edu",
        "knowledge.wharton.upenn.edu",
        "ycombinator.com",
    ),
    QuestionDomain.HISTORY: (
        "jstor.org",
        "britannica.com",
        "history.com",
        "smithsonianmag.com",
        "nationalgeographic.com",
        "archives.gov",
        "loc.gov",
        "bl.uk",
        "europeana.eu",
        "oxfordreference.com",
        "cambridge.org",
        "perseus.tufts.edu",
        "worldhistory.org",
    ),
    QuestionDomain.EDUCATION: (
        "oecd.org",
        "unesco.org",
        "ed.gov",
        "nces.ed.gov",
        "edsurge.com",
        "insidehighered.com",
        "chronicle.com",
        "edutopia.org",
        "edweek.org",
        "harvard.edu",
        "mit.edu",
        "stanford.edu",
        "ox.ac.uk",
        "cam.ac.uk",
        "coursera.org",
        "edx.org",
        "ocw.mit.edu",
        "khanacademy.org",
        "futurelearn.com",
    ),
    QuestionDomain.LIFESTYLE: (
        "nytimes.com",
        "theatlantic.com",
        "newyorker.com",
        "nationalgeographic.com",
        "vox.com",
        "theguardian.com",
        "bbc.com",
        "npr.org",
        "smithsonianmag.com",
    ),
    QuestionDomain.SOFTWARE_ENGINEERING: (
        # Language official docs / standards
        "docs.python.org",
        "go.dev",
        "rust-lang.org",
        "kotlinlang.org",
        "typescriptlang.org",
        "ecma-international.org",
        "openjdk.org",
        "swift.org",
        # Databases & data stores (official)
        "postgresql.org",
        "mongodb.com",
        "redis.io",
        "sqlite.org",
        "mysql.com",
        "cassandra.apache.org",
        "elastic.co",
        "kafka.apache.org",
        # Frameworks / runtimes (official)
        "react.dev",
        "vuejs.org",
        "angular.dev",
        "svelte.dev",
        "nextjs.org",
        "nodejs.org",
        "deno.com",
        "bun.sh",
        "spring.io",
        "django.com",
        "fastapi.tiangolo.com",
        # Cloud / infra (official)
        "kubernetes.io",
        "docker.com",
        "cncf.io",
        "docs.aws.amazon.com",
        "cloud.google.com",
        "learn.microsoft.com",
        "docs.docker.com",
        # Web standards
        "developer.mozilla.org",
        "web.dev",
        "w3.org",
        "ietf.org",
        "whatwg.org",
        # Security & quality
        "owasp.org",
        "nist.gov",
        # Architecture authorities & well-curated engineering writing
        "martinfowler.com",
        "thoughtworks.com",
        "infoq.com",
        "ieee.org",
        "acm.org",
        "oreilly.com",
        "sigplan.org",
        "sigmod.org",
        # Code & evidence repositories
        "github.com",
        # Academic CS
        "arxiv.org",
        "semanticscholar.org",
        "openalex.org",
        "dl.acm.org",
        "papers.ssrn.com",
    ),
}


def allowlist_for(domain: QuestionDomain | None) -> tuple[str, ...]:
    """Return the curated whitelist for ``domain`` (empty tuple if absent).

    ``None`` and :attr:`QuestionDomain.OTHER` both return ``()`` so the
    planner knows to fall back to :mod:`app.agent.dynamic_allowlist`.
    """
    if domain is None or domain is QuestionDomain.OTHER:
        return ()
    return WHITELIST.get(domain, ())
